version: "3.0"
services:
  discord:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "discord"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/11223344556677889900/TK472c658972dh4"
      MESSAGE_LABEL: "alertMessage"
    ports:
      - 80:80
